### PR TITLE
Support extracting data from sections section of Password type

### PR DESCRIPTION
**Pull request by caglar10ur**
This way you can have a Password type for your thing and store related metadata in the sections and extract them as needed. Eg;

```
1pass -pr Secret_DB_Credentials hostname
1pass -pr Secret_DB_Credentials encoding
1pass -pr Secret_DB_Credentials timeout
1pass -pr Secret_DB_Credentials database
....
```

### CODE REVIEW

**Comment by dcreemer** [comment]
thanks for the PR I will look into this. Is this something you might want to implement?

**Comment by caglar10ur** [comment]
@dcreemer I'm not sure I understood your question. Are you asking if using a Password type with Sections to hold metadata is what I want to implement? If so yes - I've bunch of Password types with metadata and I wanted to use them via 1pass otherwise I would appreciate if you clarify :)

**Comment by dcreemer** [comment]
@caglar10ur -- sorry to be unclear -- I meant can you write the code to implement this? If not, I will look into it this next weekend.

**Comment by caglar10ur** [comment]
@dcreemer hmmm this PR already implements that :)

**Comment by dcreemer** [comment]
Gah! I am a fool -- I thought I was reading issues, not PRs 😭 . I will review & merge right away.

**Comment by dcreemer** [comment]
thank you @caglar10ur ! PR merged.

**Pull request merged**
